version: '3.4'

services:

  web-server:
    container_name: web-server
    build: web-server

  nginx:
    image: nginx:1.17
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./project-data/nginx-logs:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/settings:/etc/nginx/settings
    depends_on:
      - web-server

  database:
    container_name: postgres
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    volumes:
      - ./database-init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "9001:8080"
    environment: 
      ADMINER_DESIGN: flat
    depends_on:
      - database